#include "gen.h"

#include "version.h"

#include <time.h>

#include "gen-consts.h"

void gen(FILE *f, struct parse_result_s pr, struct analyse_result_s ar)
{
	time_t t;
	struct tm *ti;

	time(&t);
	ti = localtime(&t);

	fprintf(f, "/* generated by %s on %04d-%02d-%02d */\n", 
			VERSION, ti->tm_year + 1900, ti->tm_mon + 1, ti->tm_mday);

	fprintf(f, sheader);

	if (ar.uses_bool)
		fprintf(f, sbool);
	if (ar.uses_string)
		fprintf(f, sstring);
	if (ar.uses_id)
		fprintf(f, sid);
	if (ar.uses_int)
		fprintf(f, sint);
	if (ar.uses_intl)
		fprintf(f, sintl);
	if (ar.uses_intll)
		fprintf(f, sintll);
	if (ar.uses_uint)
		fprintf(f, suint);
	if (ar.uses_uintl)
		fprintf(f, suintl);
	if (ar.uses_uintll)
		fprintf(f, suintll);
	if (ar.uses_float)
		fprintf(f, sfloat);
	if (ar.uses_double)
		fprintf(f, sdouble);
	if (ar.uses_doublel)
		fprintf(f, sdoublel);

}
